//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B6C2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Donor
    {
        public int idDonor { get; set; }
        [Required]
        [Display(Name = "First Name")]
        public string firstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string lastName { get; set; }

        [Required]
        [Display(Name = "Date of birth")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime birthDate { get; set; }

        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }

        [Display(Name = "Phone number")]
        [RegularExpression("[0-9]{10,10}", ErrorMessage = "The phone number must contain 10 digits!")]
        public string phoneNumber { get; set; }
        public Nullable<int> idCenter { get; set; }
        public Nullable<int> idBlood { get; set; }

        [Display(Name = "Address")]
        public string address { get; set; }
    
        public virtual donationCenter donationCenter { get; set; }
        public virtual Blood Blood { get; set; }
    }
}

