//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B6C2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class donorTransaction
    {
        [Display(Name = "Transaction id")]
        public int id { get; set; }
        [Required]
        [Display(Name = "CNP*")]
        [RegularExpression("^[0-9]{13}$", ErrorMessage = "CNP must contain 13 digits")]
        public string cnpDonor { get; set; }
        [Required]
        [Display(Name = "Status*")]
        public string status { get; set; }
        [Required]
        [Display(Name = "Donation date*")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> donationDate { get; set; }
        
        [Display(Name = "Analysis status")]
        public string analysisStatus { get; set; }
        public Nullable<int> idPatient { get; set; }
        public Nullable<int> idCenter { get; set; }
    
        public virtual donationCenter donationCenter { get; set; }
        public virtual Donor Donor { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
